<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows10.0.19041.0</TargetFramework>
    <SupportedOSPlatformVersion>10.0.19041.0</SupportedOSPlatformVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>RoRoRo.UrOcr</AssemblyName>
    <RootNamespace>RoRoRo.UrOcr</RootNamespace>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>false</UseWindowsForms>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <StartupObject>RoRoRo.UrOcr.Program</StartupObject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="ROROROblox.PluginContract" Version="0.3.0" />
    <PackageReference Include="Grpc.Net.Client" Version="2.70.0" />
    <PackageReference Include="System.Drawing.Common" Version="10.0.0" />
    <PackageReference Include="Hardcodet.NotifyIcon.Wpf" Version="2.0.1" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="tests/**/*.cs" />
  </ItemGroup>

</Project>
